language: ruby
cache: bundler

rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

gemfile:
  - gemfiles/rails_edge.gemfile
  - gemfiles/rails_5.1_stable.gemfile
  - gemfiles/rails_5.0_stable.gemfile
  - gemfiles/rails_4.2_stable.gemfile
  - gemfiles/rails_4.1_stable.gemfile

sudo: false

cache: bundler

matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.1_stable.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4.1_stable.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0_stable.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.1_stable.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
    - gemfile: gemfiles/rails_5.1_stable.gemfile

env:
  matrix:
    - DEVISE_ORM=active_record

before_install: "[ -f ${BUNDLE_GEMFILE}.lock ] && rm ${BUNDLE_GEMFILE}.lock || true"

before_script: "bundle update"

script: "bundle exec rake test"